name: Build

on:
  push:
    branches: [master]

jobs:
  build:
    strategy:
      matrix:
        include:
          - os: ubuntu-16.04
            name: ubuntu_16
          - os: ubuntu-18.04
            name: ubuntu_18
          - os: ubuntu-20.04
            name: ubuntu_20
          - os: macos-10.15
            name: macos
          - os: windows-latest
            name: windows

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Compile using pyinstaller
        run: make pyinstaller

      - name: Testing built executable
        run: ./dist/minet/minet --version

      - name: Prepare release
        run: zip -r minet_${{ matrix.name }}.zip ./dist/minet

      - name: Temp ls
        run: ls -alh
