name: Build

on:
  release:
    types: [create]
  push:
    branches: [master]

jobs:
  build_xenial:
    runs-on: ubuntu-16.04

    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install -r requirements.txt

      - name: Compile using pyinstaller
        run: make pyinstaller

      - name: Testing built executable
        run: ./dist/minet/minet --version
